catalog/urls.py
from django.urls import path

from .apps import CatalogConfig
from .views import (contacts, ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView,
                    ProductDeleteView, BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView,
                    BlogPostDeleteView, BlogCreateView)

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', contacts, name='contacts'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('blog/list/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog/сreate/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blog/detail/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('blog/update/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('blog/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from catalog.apps import CatalogConfig
from catalog.views import ProductListView
from django.conf import settings
from django.conf.urls.static import static



#from catalog.views import home, contacts

app_name = CatalogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import home, contacts

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
]

catalog/models.py
from django.db import models
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение (превью)', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
#    manufactured_at = models.DateField(verbose_name='Дата производства')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['-created_at']


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок поста")
    slug = models.CharField(unique=True, verbose_name="Ссылка для поста")
    content = models.TextField(verbose_name="Содержимое поста")
    preview_image = models.ImageField(upload_to="products/blog/", verbose_name="Превью поста (изображение)", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Признак публикации")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ['-created_at']

catalog/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'image']

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from catalog.models import Product, BlogPost
from .forms import ProductForm
from django.db import models

from .utils.mail_newsletter import congratulate_mail_newsletter


# def product_list(request):
#     product = Product.objects.all().order_by('created_at')  # Упорядочиваем по полю created_at
#     paginator = Paginator(product, 9)  # 9 продуктов на странице
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     return render(request, 'catalog/product_list.html', {'page_obj': page_obj})
#

class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'

# def product_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     context = {"product": product}
#     return render(request, 'catalog/product_detail.html', context)


class ProductDetailView(DetailView):  # Переопределяем DetailView
    model = Product
    template_name = 'catalog/product_detail.html'


# def product_create(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('product_list')
#     else:
#         form = ProductForm()
#     return render(request, 'catalog/product_form.html', {'form': form})
#


class ProductCreateView(CreateView):  # Переопределяем CreateView для создания продукта
    model = Product
    template_name = 'catalog/product_create.html'
    # template_name = 'catalog/product_form.html'
    fields = ['name', 'description', 'price', 'category', 'image']
    success_url = reverse_lazy('catalog:product_list')


class ProductUpdateView(UpdateView):  # Переопределяем UpdateView для обновления продукта
    model = Product
    template_name = 'catalog/product_update.html'
    # template_name = 'catalog/product_form.html'
    fields = ['name', 'description', 'price', 'category', 'image']
    success_url = reverse_lazy('catalog:product_list')


class ProductDeleteView(DeleteView):
    model = Product  # Переопределяем DeleteView для удаления продукта
    fields = ['name', 'description', 'price', 'category', 'image']
    template_name = 'catalog/product_delete.html'
    success_url = reverse_lazy('catalog:product_list')


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя: {name}, Телефон: {phone}, Сообщение: {message}')

    return render(request, 'catalog/contacts.html', {'contacts': contacts})


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_detail.html'
    context_object_name = 'blogpost'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        congratulate_mail_newsletter(obj)
        return obj


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_list.html'
    context_object_name = 'blogposts'
    paginate_by = 10

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)


class BlogPostCreateView(CreateView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_form.html'
    fields = ["title", "content", "preview_image", "is_published"]
    success_url = reverse_lazy('catalog:blogpost_list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("catalog:blogpost_detail", args=[self.object.pk])


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ("title", "content", "preview_image", "is_published")
    template_name = 'catalog/blog/blogpost_form.html'
    context_object_name = 'blogpost'
    success_url = reverse_lazy('catalog:blogpost_detail')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("catalog:blogpost_detail", args=[self.object.pk])


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_confirm_delete.html'
    success_url = reverse_lazy('catalog:blogpost_list')


class BlogCreateView(TemplateView):
    template_name = 'catalog/blog.html'

catalog/templates/catalog/blog/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<h1>Удалить пост</h1>
<p>Вы уверены, что хотите удалить пост "{{ blogpost.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Да, удалить</button>
    <a href="{% url 'catalog:blogpost_detail' blogpost.pk %}" class="btn btn-xs btn-block btn-outline-primary">Отмена</a>
</form>
{% endblock %}

catalog/templates/catalog/blog/blogpost_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="p-4 p-md-5 mb-4 rounded bg-light">
    <div class="col-md-12 px-0">
      <h1 class="display-6 fst-italic">Title of a longer featured blog post</h1>
        {% if blogpost.preview_image %}
        <img src="{{ blogpost.preview_image.url }}" class="img-fluid mb-3 bd-placeholder-img" width="300" height="330" alt="{{ blogpost.title }}">
    {% endif %}
    <p>Текст: {{ blogpost.content }}</p>
    <p>Создано: {{ blogpost.created_at }}</p>
    <p>Просмотров: {{ blogpost.views_count }}</p>
    <p>Опубликовано: {% if blogpost.is_published %}Да{% else %}Нет{% endif %}</p>
    <a href="{% url 'catalog:blogpost_update' blogpost.pk %}" class="btn btn-xs btn-block btn-outline-primary">Редактировать</a>
    <a href="{% url 'catalog:blogpost_delete' blogpost.pk %}" class="btn btn-xs btn-block btn-outline-primary">Удалить</a>
    <a href="{% url 'catalog:blogpost_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/blog/blogpost_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container my-5">
        <h1>{% if object %}
            Редактировать пост
        {% else %}
            Создать пост
        {% endif %}</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {% if not object %}
                <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Создать</button>
                <a href="{% url 'catalog:blogpost_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
            {% else %}
                <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Сохранить</button>
                <a href="{% url 'catalog:blogpost_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
            {% endif %}
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/blog/blogpost_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    {% if object_list %}
        <div class="row mb-2">
        {% for blogpost in object_list %}
            {% if blogpost.is_published %}
            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
<!--                        <strong class="d-inline-block mb-2 text-success">Design</strong> -->
                        <strong class="d-inline-block mb-0 text-success" style="font-size: 0.7em;">Просмотров: {{ blogpost.views_count }}</strong>
                        <h3 class="mb-0">{{ blogpost.title }}</h3>
                        <div class="mb-1 text-muted">Создано: {{ blogpost.created_at|timesince }}</div>
                        <p class="mb-auto">{{ blogpost.content|truncatewords:20 }}</p>
                        <a href="{% url 'catalog:blogpost_detail' blogpost.pk %}" class="stretched-link">Читать далее...</a>
                    </div>
                    <div class="col-auto l-none l-lg-block">
                    {% if blogpost.preview_image %}
                        <img class="bd-placeholder-img" width="200" height="230" src="{{ blogpost.preview_image.url }}">
                    {% else %}
                        <img class="bd-placeholder-img" width="200" height="230" src="/media/no_foto.jpg">
                    {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <div class="text-center" style="font-size: 1.5rem; font-weight: bold;">
            Нет ни единого поста
        </div>
    {% endif %}
</div>
{% endblock %}