catalog/urls.py
from django.urls import path

from .apps import CatalogConfig
from .views import (contacts, ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView,
                    ProductDeleteView, BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView,
                    BlogPostDeleteView, BlogCreateView)

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', contacts, name='contacts'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('blog/list/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog/сreate/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blog/detail/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('blog/update/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('blog/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from catalog.apps import CatalogConfig
from catalog.views import ProductListView
from django.conf import settings
from django.conf.urls.static import static



#from catalog.views import home, contacts

app_name = CatalogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import home, contacts

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
]

catalog/models.py
from django.db import models
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение (превью)', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
#    manufactured_at = models.DateField(verbose_name='Дата производства')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['-created_at']


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок поста")
    slug = models.CharField(unique=True, verbose_name="Ссылка для поста")
    content = models.TextField(verbose_name="Содержимое поста")
    preview_image = models.ImageField(upload_to="products/blog/", verbose_name="Превью поста (изображение)", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Признак публикации")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ['-created_at']

catalog/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'image']

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from catalog.models import Product, BlogPost
from .forms import ProductForm
from django.db import models

from .utils.mail_newsletter import congratulate_mail_newsletter


# def product_list(request):
#     product = Product.objects.all().order_by('created_at')  # Упорядочиваем по полю created_at
#     paginator = Paginator(product, 9)  # 9 продуктов на странице
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     return render(request, 'catalog/product_list.html', {'page_obj': page_obj})
#

class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'

# def product_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     context = {"product": product}
#     return render(request, 'catalog/product_detail.html', context)


class ProductDetailView(DetailView):  # Переопределяем DetailView
    model = Product
    template_name = 'catalog/product_detail.html'


# def product_create(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('product_list')
#     else:
#         form = ProductForm()
#     return render(request, 'catalog/product_form.html', {'form': form})
#


class ProductCreateView(CreateView):  # Переопределяем CreateView для создания продукта
    model = Product
    template_name = 'catalog/product_create.html'
    # template_name = 'catalog/product_form.html'
    fields = ['name', 'description', 'price', 'category', 'image']
    success_url = reverse_lazy('catalog:product_list')


class ProductUpdateView(UpdateView):  # Переопределяем UpdateView для обновления продукта
    model = Product
    template_name = 'catalog/product_update.html'
    # template_name = 'catalog/product_form.html'
    fields = ['name', 'description', 'price', 'category', 'image']
    success_url = reverse_lazy('catalog:product_list')


class ProductDeleteView(DeleteView):
    model = Product  # Переопределяем DeleteView для удаления продукта
    fields = ['name', 'description', 'price', 'category', 'image']
    template_name = 'catalog/product_delete.html'
    success_url = reverse_lazy('catalog:product_list')


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя: {name}, Телефон: {phone}, Сообщение: {message}')

    return render(request, 'catalog/contacts.html', {'contacts': contacts})


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_detail.html'
    context_object_name = 'blogpost'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        congratulate_mail_newsletter(obj)
        return obj


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_list.html'
    context_object_name = 'blogposts'
    paginate_by = 10

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)


class BlogPostCreateView(CreateView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_form.html'
    fields = ["title", "content", "preview_image", "is_published"]
    success_url = reverse_lazy('catalog:blogpost_list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("catalog:blogpost_detail", args=[self.object.pk])


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ("title", "content", "preview_image", "is_published")
    template_name = 'catalog/blog/blogpost_form.html'
    context_object_name = 'blogpost'
    success_url = reverse_lazy('catalog:blogpost_detail')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("catalog:blogpost_detail", args=[self.object.pk])


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = 'catalog/blog/blogpost_confirm_delete.html'
    success_url = reverse_lazy('catalog:blogpost_list')


class BlogCreateView(TemplateView):
    template_name = 'catalog/blog.html'

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css'  %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}">
    <style>
        body {
            padding-top: 60px; /* Adjust based on the height of your navbar */
        }
    </style>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-1 px-md-2 mb-1 bg-white border-bottom box-shadow fixed-top">
    <h4 class="my-0 mr-md-auto font-weight-normal">MARKET_SKY</h4>
    <nav class="ms-2">
        <a class="p-2 btn btn-outline-primary" href={% url 'catalog:product_list' %}>Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:blogpost_list' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:blogpost_create' %}">Создать пост</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>


<div class="pricing-header px-1 py-1 pt-md-2 pb-md-2 mx-auto text-center">
    <h5 class="display-6 text-center">MARKET_SKY</h5>
<!--    <p class="lead">MARKET_SKY - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p> -->
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Контактный телефон" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product.html
<!-- templates/catalog/product.html -->
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image | media_files }}" class="img-fluid" alt="{{ product.name }}">
        </div>
        <div class="col-md-6">
            <h3>{{ product.name }}</h3>
            <p>Категория: {{ product.category.name }}</p>
            <p>Цена: {{ product.price }} ₽</p>
            <p>Описание: {{ product.description }}</p>
            <button type="button" class="btn btn-primary">Купить</button>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_create.html
<!-- templates/catalog/product_create.html -->
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center calc">
        <h2>Создать продукт</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Сохранить</button>
                <a href="{% url 'catalog:product_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
            </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_delete.html
<!-- templates/catalog/product_delete.html-->
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center calc">
            <h2>Вы уверены, что хотите удалить продукт ? </h2>
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}
                <div class="col-md-5">
                    <img src="{{ product.image | media_files }}" class="img-fluid" alt="{{ product.name }}">
                </div>
                <div class="col-md-6">
                    <h3>{{ product.name }}</h3>
                    <p>Категория: {{ product.category.name }}</p>
                    <p>Цена: {{ product.price }} ₽</p>
                    <p>Описание: {{ product.description }}</p>
                    <button type="submit" class="btn btn-danger">Да,удалить</button>
                    <a class="btn btn-xs btn-block btn-outline-primary" href="{% url 'catalog:product_list'  %}">Отменить</a>
                    </div>
            </form>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
<!-- templates/catalog/product_detail.html -->
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image | media_files }}" class="img-fluid" alt="{{ product.name }}">
        </div>
        <div class="col-md-6">
            <h3>{{ product.name }}</h3>
            <p>Категория: {{ product.category.name }}</p>
            <p>Цена: {{ product.price }} ₽</p>
            <p>Описание: {{ product.description }}</p>
            <button type="button" class="btn btn-xs btn-block btn-outline-primary">Купить</button>
            <a href="{% url 'catalog:product_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
<!-- templates/catalog/product_form.html -->
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center calc">
        {% if object.id  %}
        <h2>Изменить продукт</h2>
        {% else %}
        <h2>Создать продукт</h2>
        {% endif  %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
<!-- templates/catalog/product_list.html -->
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    {% for product in object_list %}
        <div class="p-1 col-4">
            <div class="card mx-auto">
                <div class="card-header div-fixed-size">
                    <img src="{{ product.image | media_files }}" class="img-fluid" style="height: 300px;">
                </div>
                <div class="card-body">
                    <ul class="mt-2 mb-2 text-start">
<!--                       <li>Продукт: {{ product.name | slice:":30" }}</li>-->
                        <li>Продукт: {{ product.name | truncate_chars:30 }}</li>
                        <li>Категория: {{ product.category.name | truncate_chars:30 }}</li>
                        <li>Цена: {{ product.price }} ₽</li>
                    </ul>
                    <button class="btn btn-xs btn-block btn-outline-primary">Купить</button>
                    <a class="btn btn-xs btn-block btn-outline-primary" href="{% url 'catalog:product_detail' product.pk %}">Подробно</a>
                    <a class="btn btn-xs btn-block btn-outline-primary" href="{% url 'catalog:product_update' product.pk %}">Изменить</a>
                    <a class="btn btn-xs btn-block btn-outline-primary" href="{% url 'catalog:product_delete' product.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<!-- Пагинация -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">Первый</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущий</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующий</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последний</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

catalog/templates/catalog/product_update.html
<!-- templates/catalog/product_update.html -->
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center calc">
        <h2>Изменить продукт</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
    </div>
</div>
{% endblock %}